name: update maintainer data cronjob

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 20 1 * *"

jobs:
  updateProjectData:
    permissions:
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
      - run: |
          python3.12 -m venv venv
          source venv/bin/activate
          python3.12 -m pip install -r ./project/requirements.txt
      - run: |
          source venv/bin/activate
          ./project/bin/get_maintainer_data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Update maintainer data
          signoff: true
          token: ${{ secrets.GITHUB_TOKEN }}
